### ISSUE TITLE
流程中可能存在公式错误

### ISSUE THREAD

**Issue by ABILIBILI** [Xingyb14/curves_for_object_detection#1]
你好,
原文:
从上到下截取数组 tf_confidence 的前 1，2，3，…，M 行，每次截取都得到一个子数组，子数组中 1 的个数即为 tp，0 的个数即为 fp，查全率 `recall = tp / (tp + fp)`，查准率 `precision / TPR = tp / (groundtruth boundingbox 的个数)`。每次截取得到一个点，这样就一共得到 M 个点。以 fp 为横坐标，TPR 为纵坐标绘制出 ROC 曲线；以 recall 为横坐标，precision 为纵坐标绘制出 PR 曲线。
我感觉应该是:
查全率 ` recall = tp / (groundtruth boundingbox 的个数)`，查准率 `precision / TPR = tp / ((tp + fp)`
如有错误请见谅:D

**Comment by Xingyb14** [comment]
的确是在 README 中写错了，感谢指正！
